### ISSUE TITLE
[Bug] Config option for embodies not attacking skeletons doesn't work

### ISSUE THREAD

**Issue by evanbones** [infernalexp/Infernal-Expansion#11]
As the title says, it just doesn't do anything. The other AI config options seem to work fine. No matter what it's set at, embodies will still attack skeletons. Luckily, this will probably be a nonissue if there's an embody rework in the future.

**Comment by Dariensg** [comment]
Thank you for pointing this out! This was a slight error on my part. The config will disable Skeletons targeting the Embodies first, but the Embodies will still target skeletons, initiating a fight between them. Since we're trying to move on from Release 1, I'll get a fix for this and all other custom mob configs into Release 2 for you!

**Comment by SwanX1** [comment]
Fixed as of commit a8615a7
